/**
 * Author:  hjd
 * Description: Find the transactional account per client with the highest balance
 */
SELECT C.CLIENT_ID as "Client Id", C.SURNAME as "Client Surname", CA.CLIENT_ACCOUNT_NUMBER as "Client Account Number", T.DESCRIPTION as "Account Description" ,MAXBALANCE as "Display Balance"
FROM CLIENT C 
LEFT JOIN (
    SELECT A.CLIENT_ID, MAX(A.DISPLAY_BALANCE)  AS MAXBALANCE
    FROM CLIENT_ACCOUNT A GROUP BY A.CLIENT_ID 
) M ON M.CLIENT_ID = C.CLIENT_ID
LEFT JOIN CLIENT_ACCOUNT CA ON CA.CLIENT_ID = M.CLIENT_ID AND  CA.DISPLAY_BALANCE =  MAXBALANCE
LEFT JOIN ACCOUNT_TYPE T ON T.ACCOUNT_TYPE_CODE  = CA.ACCOUNT_TYPE_CODE ORDER BY MAXBALANCE DESC;


/**
 * Author:  hjd
 * Description: Calculate aggregate financial position per client
 */
SELECT CONCAT(C.TITLE, '  ', C.NAME ,'  ',C.SURNAME) as "Client"  ,LOAN.LOANBALANCE AS "Loan Balance", TRAN.TRANSACTIONBALANCE AS "Transactional Balance", EXPO.TOTALEXPO AS "Net Position"
FROM CLIENT C
LEFT JOIN (SELECT A.CLIENT_ID, SUM(A.DISPLAY_BALANCE)  AS TRANSACTIONBALANCE
          FROM CLIENT_ACCOUNT A  
          JOIN ACCOUNT_TYPE T ON T.ACCOUNT_TYPE_CODE  = A.ACCOUNT_TYPE_CODE
          WHERE T.TRANSACTIONAL = 'true'
          GROUP BY A.CLIENT_ID, T.TRANSACTIONAL) TRAN 
ON TRAN.CLIENT_ID = C.CLIENT_ID
LEFT JOIN (SELECT A.CLIENT_ID, SUM(A.DISPLAY_BALANCE)  AS LOANBALANCE
          FROM CLIENT_ACCOUNT A  
          WHERE A.ACCOUNT_TYPE_CODE  = 'HLOAN' OR A.ACCOUNT_TYPE_CODE  = 'PLOAN'
          GROUP BY A.CLIENT_ID) LOAN 
ON LOAN.CLIENT_ID = C.CLIENT_ID
LEFT JOIN (SELECT A.CLIENT_ID, SUM(A.DISPLAY_BALANCE)  AS TOTALEXPO
          FROM CLIENT_ACCOUNT A  
          GROUP BY A.CLIENT_ID) EXPO
ON EXPO.CLIENT_ID = C.CLIENT_ID;
